project_name: gmc
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - dir: .
  - main: ./cmd/gmc/main.go
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gmc