builds:
  - id: linux-amd64
    binary: kink-linux-{{ .Arch }}
    main: ./cmd/gmc/main.go
    goos:
      - linux
    goarch:
      - amd64
    no_unique_dist_dir: true

  - id: darwin-amd64
    binary: kink-darwin-{{ .Arch }}
    main: ./cmd/gmc/main.go
    goos:
      - darwin
    goarch:
      - amd64
    no_unique_dist_dir: true

  - id: windows-amd64
    binary: kink-windows-{{ .Arch }}
    main:  ./cmd/gmc/main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe
    no_unique_dist_dir: true