Server:
  port: 8080
Smtp:
  Host: HOST
  Port: PORT
  From: FROM_EMAIL
  Password: FROM_EMAIL_PASSWORD
Mongo:
  username: USERNAME
  password: PASSWORD
  database: DB
  collection: COLLECTION
Firestore:
  projectID: PROJECT_ID
  sectionsCollectionID: SECTIONS_COLLECTION_ID
  usersCollectionID: USERS_COLLECTION_ID
  credentialsPath: PATH_TO_CREDENTIALS